# CircleCI configuration file

version: 2.1
jobs:
  build:
    macos:
      xcode: "26.0.1"
      # resource_class: m4pro.medium
    steps:
      - checkout
      - run: swift build -v

  test:
    macos:
      xcode: "26.0.1"
      #resource_class: m4pro.medium
    steps:
      - checkout
      - run: swift test -v

workflows:
  build-and-test:
    jobs:
      - build
      - test