# CircleCI configuration file

version: 2.1
jobs:
  build:
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run: swift build -v

  test:
    macos:
      xcode: "16.0.0"
    steps:
      - checkout
      - run: swift test -v

workflows:
  build-and-test:
    jobs:
      - build
      - test