# CircleCI configuration file

version: 2.1

jobs:
  build:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
        name: Build
        command: swift build -v

  test:
    macos:
      xcode: 15.4.0
    steps:
      - checkout
      - run:
        name: Test
        command: swift test -v
